"""
routers/study_seed_tech.py
==========================
Study Material ka SEED content — part 2: machine ke parts aur systems
(Sensors, Pneumatic, Hydraulic, Electrical, Control/PLC-HMI, Mechanical,
Safety).

Har topic ka dhancha:  (category, title, body_en, body_hi)

Hindi hissa DEVANAGARI me hai.  Acronym aur part ke naam (PLC, HMI, VFD,
MCB, SMPS, FRL, PNP/NPN, LOTO, PPE) Latin me hi rakhe gaye hain — Hindi ke
technical document me bhi wo aise hi likhe jaate hain, aur shop floor par
wahi padha jaata hai.

Har topic ke aakhir me "COMMON FAULTS / आम दिक्कतें" jaan-boojh kar rakha
hai — padhne wala aksar kisi dikkat ke waqt hi yahan aata hai, to seedhe
kaam ki baat mil jaye.

Seed sirf pehli baar chalta hai (table bilkul khali ho tab).  Uske baad
admin page se hi sab kuch badalta hai — is file ko chhune ki zaroorat nahi.
"""

TECH = [
    # ── Sensors ─────────────────────────────────────────────────────────
    ("Sensors", "What is a Sensor?",
     "A sensor is a device that senses something on the machine - a part "
     "present, a cylinder at the end, a level, a pressure, a temperature - and "
     "sends the PLC a simple ON/OFF (or a value).\n\n"
     "Most machine sensors are 24V DC and have 3 wires: brown (+24V), blue "
     "(0V) and black (signal).\n\n"
     "PNP type switches the SIGNAL to +24V when it senses. NPN switches it to "
     "0V. Fitting the wrong type is a very common mistake - the sensor light "
     "glows but the PLC input never comes ON.\n\n"
     "COMMON FAULTS: dirty face, sensing distance too far, loose connector, "
     "cable broken at the drag chain, wrong PNP/NPN type.",
     "सेंसर वह डिवाइस है जो मशीन पर कुछ महसूस करता है — पार्ट आया या नहीं, "
     "सिलेंडर एंड पर पहुँचा या नहीं, लेवल, प्रेशर, तापमान — और PLC को एक सीधा "
     "ON/OFF (या कोई वैल्यू) भेज देता है।\n\n"
     "ज़्यादातर मशीन सेंसर 24V DC के होते हैं और उनमें 3 तार होते हैं: ब्राउन "
     "(+24V), ब्लू (0V) और ब्लैक (सिग्नल)।\n\n"
     "PNP टाइप सेंस करने पर सिग्नल को +24V पर ले जाता है। NPN उसे 0V पर ले "
     "जाता है। गलत टाइप लगा देना बहुत आम गलती है — सेंसर की लाइट जलती है पर "
     "PLC का इनपुट कभी ON ही नहीं होता।\n\n"
     "आम दिक्कतें: सेंसर का फ़ेस गंदा, सेंसिंग दूरी ज़्यादा, कनेक्टर ढीला, ड्रैग "
     "चेन में केबल टूटा, गलत PNP/NPN टाइप।"),

    ("Sensors", "Proximity Sensor (Inductive)",
     "An inductive proximity sensor detects METAL without touching it. It is "
     "the most used sensor on our machines - to confirm a cylinder position, a "
     "fixture closed, or a metal part present.\n\n"
     "It only senses metal. Sensing distance is small (usually 2-8 mm) and it "
     "REDUCES for non-ferrous metal like aluminium or brass - roughly half for "
     "aluminium compared to mild steel.\n\n"
     "COMMON FAULTS: gap increased due to loosening or vibration, metal chips "
     "stuck on the face, sensor knocked out of position by the part, water/oil "
     "ingress in the connector.",
     "इंडक्टिव प्रॉक्सिमिटी सेंसर बिना छुए धातु (मेटल) को पकड़ता है। हमारी "
     "मशीनों पर सबसे ज़्यादा इसी का इस्तेमाल होता है — सिलेंडर की पोज़िशन "
     "कन्फ़र्म करने, फ़िक्स्चर बंद हुआ या नहीं, या मेटल पार्ट है या नहीं।\n\n"
     "यह सिर्फ़ मेटल को पकड़ता है। सेंसिंग दूरी कम होती है (आम तौर पर 2–8 मिमी) "
     "और एल्युमिनियम/ब्रास जैसी नॉन-फ़ेरस धातु पर यह और घट जाती है — माइल्ड "
     "स्टील के मुक़ाबले एल्युमिनियम पर लगभग आधी।\n\n"
     "आम दिक्कतें: ढीला होने या वाइब्रेशन से गैप बढ़ जाना, फ़ेस पर मेटल के चिप्स "
     "चिपक जाना, पार्ट की चोट से सेंसर का अपनी जगह से हट जाना, कनेक्टर में "
     "पानी/तेल चला जाना।"),

    ("Sensors", "Capacitive Sensor",
     "A capacitive sensor detects almost ANY material - plastic, water, oil, "
     "powder, wood - not just metal. It is used for level detection in tanks "
     "and hoppers, and for non-metal parts.\n\n"
     "Because it senses everything, it is also easily fooled: dust, moisture or "
     "an oil film on the face can hold it ON. Most have a small sensitivity "
     "screw to set the trip point.\n\n"
     "COMMON FAULTS: sensitivity set too high, condensation or oil film on the "
     "face, wrong material in front of it, temperature drift.",
     "कैपेसिटिव सेंसर लगभग हर चीज़ पकड़ता है — प्लास्टिक, पानी, तेल, पाउडर, "
     "लकड़ी — सिर्फ़ मेटल नहीं। इसका इस्तेमाल टैंक/हॉपर में लेवल देखने और "
     "नॉन-मेटल पार्ट्स के लिए होता है।\n\n"
     "क्योंकि यह सब कुछ पकड़ता है, इसलिए आसानी से धोखा भी खा जाता है: धूल, नमी "
     "या फ़ेस पर तेल की परत इसे ON ही रख सकती है। ज़्यादातर में एक छोटा "
     "सेंसिटिविटी स्क्रू होता है जिससे ट्रिप पॉइंट सेट किया जाता है।\n\n"
     "आम दिक्कतें: सेंसिटिविटी ज़्यादा सेट हो जाना, फ़ेस पर नमी या तेल की परत, "
     "सामने गलत मटीरियल आ जाना, तापमान से ड्रिफ़्ट।"),

    ("Sensors", "Photoelectric Sensor",
     "A photoelectric sensor works on light. Three common types:\n\n"
     "THROUGH BEAM - transmitter one side, receiver the other. Longest range, "
     "most reliable.\n"
     "RETRO-REFLECTIVE - sensor and a reflector; beam goes and comes back.\n"
     "DIFFUSE - sensor alone; light bounces off the part itself. Shortest "
     "range, most affected by part colour and surface.\n\n"
     "COMMON FAULTS: lens or reflector dirty, alignment disturbed, a shiny part "
     "reflecting when it should not, strong ambient light, black/matt parts not "
     "reflecting enough for a diffuse type.",
     "फ़ोटोइलेक्ट्रिक सेंसर रोशनी पर काम करता है। तीन आम टाइप:\n\n"
     "THROUGH BEAM — एक तरफ़ ट्रांसमीटर, दूसरी तरफ़ रिसीवर। सबसे लंबी रेंज, "
     "सबसे भरोसे का।\n"
     "RETRO-REFLECTIVE — सेंसर और एक रिफ़्लेक्टर; बीम जाकर वापस आती है।\n"
     "DIFFUSE — अकेला सेंसर; रोशनी पार्ट से ही टकराकर लौटती है। सबसे छोटी रेंज, "
     "और पार्ट के रंग/सरफ़ेस का सबसे ज़्यादा असर।\n\n"
     "आम दिक्कतें: लेंस या रिफ़्लेक्टर गंदा, एलाइनमेंट हिल जाना, चमकदार पार्ट का "
     "बेवजह रिफ़्लेक्शन, तेज़ आसपास की रोशनी, डिफ़्यूज़ टाइप पर काले/मैट पार्ट "
     "का ठीक से रिफ़्लेक्ट न करना।"),

    ("Sensors", "Limit Switch",
     "A limit switch is a mechanical switch operated by a lever, roller or "
     "plunger that the moving part physically pushes. Simple and cheap, and it "
     "gives a definite contact - which is why it is still used for safety and "
     "end-of-travel positions.\n\n"
     "It has NO (normally open) and NC (normally closed) contacts. Safety "
     "circuits normally use the NC contact, so a broken wire also trips the "
     "circuit.\n\n"
     "COMMON FAULTS: worn or bent lever, contact burnt or oxidised, mounting "
     "loose so the actuation point shifted, water inside the body.",
     "लिमिट स्विच एक मैकेनिकल स्विच है जिसे लीवर, रोलर या प्लंजर से चलता हुआ "
     "पार्ट ख़ुद दबाता है। सीधा और सस्ता, और यह पक्का कॉन्टैक्ट देता है — इसीलिए "
     "आज भी सेफ़्टी और एंड-ऑफ़-ट्रैवल के लिए चलता है।\n\n"
     "इसमें NO (नॉर्मली ओपन) और NC (नॉर्मली क्लोज़्ड) कॉन्टैक्ट होते हैं। सेफ़्टी "
     "सर्किट में आम तौर पर NC कॉन्टैक्ट लगता है, ताकि तार टूट जाए तो भी सर्किट "
     "ट्रिप हो जाए।\n\n"
     "आम दिक्कतें: लीवर घिस जाना या मुड़ जाना, कॉन्टैक्ट जल जाना या काला पड़ "
     "जाना, माउंटिंग ढीला होने से दबने का पॉइंट खिसक जाना, बॉडी में पानी।"),

    ("Sensors", "Reed Switch (Cylinder Sensor)",
     "A reed switch is the small sensor clamped on the OUTSIDE of a pneumatic "
     "cylinder barrel. The piston inside carries a magnet; when it comes near, "
     "the reed contacts close and the PLC knows the cylinder reached that "
     "end.\n\n"
     "Every automatic cylinder normally has two - one for home, one for work "
     "position.\n\n"
     "COMMON FAULTS: clamp loosened by vibration so the switch slid along the "
     "barrel, LED glows but contact welded, cable damaged where it bends, and "
     "cylinder speed so high that the magnet passes before the switch responds.",
     "रीड स्विच वह छोटा सेंसर है जो न्यूमैटिक सिलेंडर की बैरल के बाहर क्लैंप से "
     "लगा होता है। अंदर पिस्टन पर मैग्नेट होता है; जब वह पास आता है तो रीड का "
     "कॉन्टैक्ट जुड़ जाता है और PLC को पता चल जाता है कि सिलेंडर उस एंड तक "
     "पहुँच गया।\n\n"
     "हर ऑटोमैटिक सिलेंडर पर आम तौर पर दो होते हैं — एक होम के लिए, एक वर्क "
     "पोज़िशन के लिए।\n\n"
     "आम दिक्कतें: वाइब्रेशन से क्लैंप ढीला होकर स्विच का बैरल पर खिसक जाना, LED "
     "जलती है पर कॉन्टैक्ट चिपक (वेल्ड) गया, झुकने वाली जगह पर केबल ख़राब, और "
     "सिलेंडर इतना तेज़ कि मैग्नेट स्विच के रेस्पॉन्स से पहले ही निकल जाए।"),

    ("Sensors", "Pressure Switch",
     "A pressure switch watches air or oil pressure and gives an ON/OFF signal "
     "when the pressure crosses a set point. It is what stops the machine from "
     "running on low air.\n\n"
     "Do not confuse it with a pressure TRANSMITTER, which sends a continuous "
     "value (4-20 mA or 0-10 V) instead of ON/OFF.\n\n"
     "COMMON FAULTS: set point drifted, diaphragm damaged, port choked with "
     "dirt or moisture, and the switch reading fine while the actual problem is "
     "a leak downstream keeping real pressure low.",
     "प्रेशर स्विच हवा या तेल का प्रेशर देखता है और सेट पॉइंट पार होने पर ON/OFF "
     "सिग्नल देता है। कम हवा पर मशीन को चलने से यही रोकता है।\n\n"
     "इसे प्रेशर ट्रांसमीटर से मत मिलाइए — ट्रांसमीटर ON/OFF के बजाय लगातार "
     "वैल्यू भेजता है (4–20 mA या 0–10 V)।\n\n"
     "आम दिक्कतें: सेट पॉइंट खिसक जाना, डायाफ़्राम ख़राब, पोर्ट में गंदगी या नमी "
     "से चोकिंग, और स्विच तो ठीक पढ़ रहा हो पर असली दिक्कत आगे कहीं लीकेज हो जो "
     "प्रेशर गिराती रहती है।"),

    ("Sensors", "Encoder",
     "An encoder converts movement into pulses so the PLC can measure position "
     "or speed. A rotary encoder on a shaft, or a linear scale on a slide.\n\n"
     "INCREMENTAL type only sends pulses - position is counted from a home "
     "reference, so it must be homed after every power off.\n"
     "ABSOLUTE type sends the actual position, so homing is not needed.\n\n"
     "COMMON FAULTS: coupling loose or slipping so counts drift, cable "
     "screening broken causing noise and wrong counts, home sensor faulty so "
     "homing itself is wrong, dirt on a linear scale.",
     "एनकोडर मूवमेंट को पल्स में बदल देता है, ताकि PLC पोज़िशन या स्पीड नाप सके। "
     "शाफ़्ट पर रोटरी एनकोडर, या स्लाइड पर लीनियर स्केल।\n\n"
     "INCREMENTAL टाइप सिर्फ़ पल्स भेजता है — पोज़िशन होम रेफ़रेंस से गिनी जाती "
     "है, इसलिए हर पावर ऑफ़ के बाद होमिंग ज़रूरी है।\n"
     "ABSOLUTE टाइप असली पोज़िशन भेजता है, इसलिए होमिंग की ज़रूरत नहीं।\n\n"
     "आम दिक्कतें: कपलिंग ढीला या स्लिप होने से काउंट खिसक जाना, केबल की "
     "शील्डिंग टूटने से नॉइज़ और गलत काउंट, होम सेंसर ख़राब होने से होमिंग ही "
     "गलत, लीनियर स्केल पर गंदगी।"),

    # ── Pneumatic ───────────────────────────────────────────────────────
    ("Pneumatic", "What is a Pneumatic System?",
     "A pneumatic system uses COMPRESSED AIR to do work - clamping, pushing, "
     "lifting, blowing.\n\n"
     "The path is always the same: compressor -> receiver tank -> main line -> "
     "FRL unit -> solenoid valve -> cylinder.\n\n"
     "Air is clean, cheap and safe, but it is COMPRESSIBLE - so pneumatic "
     "motion is springy and cannot hold an exact mid position or a very high "
     "force. That is where hydraulics is used instead.\n\n"
     "Typical machine line pressure is around 5-6 bar.\n\n"
     "COMMON FAULTS: low line pressure, leakage, water in the line, choked "
     "filter.",
     "न्यूमैटिक सिस्टम दबाई हुई हवा से काम करता है — क्लैंपिंग, धकेलना, उठाना, "
     "ब्लोइंग।\n\n"
     "रास्ता हमेशा एक ही होता है: कंप्रेसर → रिसीवर टैंक → मेन लाइन → FRL यूनिट "
     "→ सोलेनॉइड वाल्व → सिलेंडर।\n\n"
     "हवा साफ़, सस्ती और सुरक्षित है, पर यह दबती है — इसलिए न्यूमैटिक मूवमेंट "
     "थोड़ी स्प्रिंगी होती है और बीच में सटीक पोज़िशन या बहुत ज़्यादा फ़ोर्स नहीं "
     "रोक सकती। वहाँ हाइड्रोलिक का इस्तेमाल होता है।\n\n"
     "मशीन लाइन का आम प्रेशर लगभग 5–6 बार होता है।\n\n"
     "आम दिक्कतें: लाइन प्रेशर कम, लीकेज, लाइन में पानी, फ़िल्टर चोक।"),

    ("Pneumatic", "Pneumatic Cylinder",
     "A cylinder converts air pressure into straight-line movement. Air pushes "
     "the piston, the rod moves out or in.\n\n"
     "SINGLE ACTING - air on one side, a spring returns it.\n"
     "DOUBLE ACTING - air on both sides, powered both ways. Almost all machine "
     "cylinders are double acting.\n\n"
     "Force depends on bore size and pressure, not on the flow. Speed depends "
     "on flow, which is set by the speed-control (flow control) fittings on the "
     "ports.\n\n"
     "COMMON FAULTS: seal worn so it leaks and loses force, rod bent from side "
     "load, cushion screw wrongly set causing banging at ends, mounting bolts "
     "loose, speed control choked or fully opened.",
     "सिलेंडर हवा के प्रेशर को सीधी लाइन की मूवमेंट में बदलता है। हवा पिस्टन को "
     "धकेलती है और रॉड बाहर या अंदर जाता है।\n\n"
     "SINGLE ACTING — एक तरफ़ हवा, वापस स्प्रिंग लाता है।\n"
     "DOUBLE ACTING — दोनों तरफ़ हवा, दोनों तरफ़ ताक़त से चलता है। मशीन के लगभग "
     "सारे सिलेंडर डबल एक्टिंग ही होते हैं।\n\n"
     "फ़ोर्स बोर के साइज़ और प्रेशर पर निर्भर करता है, फ़्लो पर नहीं। स्पीड फ़्लो "
     "पर निर्भर करती है, जो पोर्ट पर लगे स्पीड-कंट्रोल (फ़्लो कंट्रोल) से सेट "
     "होती है।\n\n"
     "आम दिक्कतें: सील घिस जाने से लीकेज और फ़ोर्स कम, साइड लोड से रॉड मुड़ "
     "जाना, कुशन स्क्रू गलत सेट होने से एंड पर ठोक, माउंटिंग बोल्ट ढीले, स्पीड "
     "कंट्रोल चोक या पूरा खुला।"),

    ("Pneumatic", "Solenoid Valve",
     "A solenoid valve is the electrical switch for air. The PLC energises the "
     "coil, the spool shifts, and air is sent to one side of the cylinder.\n\n"
     "5/2 valve - 5 ports, 2 positions. The normal valve for a double acting "
     "cylinder.\n"
     "SINGLE SOLENOID returns by spring when de-energised; DOUBLE SOLENOID "
     "stays where it was until the other coil is energised.\n\n"
     "Every valve has a MANUAL OVERRIDE button - very useful to check whether "
     "the fault is electrical or pneumatic.\n\n"
     "COMMON FAULTS: coil burnt, spool stuck due to dirt or no lubrication, no "
     "24V reaching the coil, silencer on the exhaust port choked (cylinder "
     "becomes slow or does not return).",
     "सोलेनॉइड वाल्व हवा का इलेक्ट्रिकल स्विच है। PLC कॉइल को सप्लाई देता है, "
     "स्पूल खिसकता है, और हवा सिलेंडर की एक तरफ़ चली जाती है।\n\n"
     "5/2 वाल्व — 5 पोर्ट, 2 पोज़िशन। डबल एक्टिंग सिलेंडर के लिए आम वाल्व।\n"
     "SINGLE SOLENOID सप्लाई हटने पर स्प्रिंग से वापस आ जाता है; DOUBLE SOLENOID "
     "वहीं रुका रहता है जब तक दूसरी कॉइल को सप्लाई न मिले।\n\n"
     "हर वाल्व पर एक मैनुअल ओवरराइड बटन होता है — यह जाँचने के लिए बहुत काम का "
     "है कि दिक्कत इलेक्ट्रिकल है या न्यूमैटिक।\n\n"
     "आम दिक्कतें: कॉइल जल जाना, गंदगी या लुब्रिकेशन न होने से स्पूल अटक जाना, "
     "कॉइल तक 24V न पहुँचना, एग्ज़ॉस्ट पोर्ट का साइलेंसर चोक (सिलेंडर धीमा हो "
     "जाता है या वापस नहीं आता)।"),

    ("Pneumatic", "FRL Unit (Filter - Regulator - Lubricator)",
     "The FRL is the air preparation unit at the machine inlet. Three parts:\n\n"
     "FILTER - removes dust and water. Its bowl must be drained.\n"
     "REGULATOR - sets and holds the machine pressure, shown on the gauge.\n"
     "LUBRICATOR - adds a fine oil mist for valves and cylinders (not used on "
     "oil-free systems).\n\n"
     "Most 'low pressure' complaints are simply a choked filter element or a "
     "full water bowl.\n\n"
     "COMMON FAULTS: filter element choked, auto-drain not working so water "
     "carries forward, regulator knob disturbed by someone, lubricator empty or "
     "dripping too fast.",
     "FRL मशीन के इनलेट पर लगी हवा तैयार करने वाली यूनिट है। तीन हिस्से:\n\n"
     "फ़िल्टर — धूल और पानी निकालता है। इसका बाउल ख़ाली करते रहना ज़रूरी है।\n"
     "रेगुलेटर — मशीन का प्रेशर सेट करके रखता है, गेज पर दिखता है।\n"
     "लुब्रिकेटर — वाल्व और सिलेंडर के लिए बारीक तेल की धुंध देता है (ऑइल-फ़्री "
     "सिस्टम पर नहीं लगता)।\n\n"
     "'प्रेशर कम है' की ज़्यादातर शिकायत असल में चोक फ़िल्टर एलिमेंट या भरा हुआ "
     "पानी का बाउल ही होती है।\n\n"
     "आम दिक्कतें: फ़िल्टर एलिमेंट चोक, ऑटो-ड्रेन काम न करना जिससे पानी आगे चला "
     "जाए, किसी ने रेगुलेटर का नॉब घुमा दिया, लुब्रिकेटर ख़ाली या ज़्यादा तेज़ "
     "टपक रहा हो।"),

    ("Pneumatic", "Air Pressure and Leakage",
     "Air leakage is the most expensive and most ignored loss in a plant. A "
     "leak does not stop the machine, so nobody reports it - but the compressor "
     "runs longer, and pressure drops when many cylinders work together.\n\n"
     "The right way to find leaks is in a silent shift: walk the line and "
     "listen, and check fittings with soap water.\n\n"
     "Watch for: pressure OK at the gauge but dropping during the cycle (a leak "
     "or an undersized pipe), and a cylinder that is slow only when other "
     "machines are running.",
     "हवा की लीकेज प्लांट का सबसे महँगा और सबसे नज़रअंदाज़ किया जाने वाला नुकसान "
     "है। लीकेज से मशीन रुकती नहीं, इसलिए कोई बताता नहीं — पर कंप्रेसर ज़्यादा "
     "देर चलता है, और जब बहुत से सिलेंडर एक साथ चलते हैं तो प्रेशर गिर जाता "
     "है।\n\n"
     "लीकेज ढूँढने का सही तरीक़ा ख़ाली शिफ़्ट में है: लाइन के साथ चलकर सुनिए, और "
     "फ़िटिंग पर साबुन-पानी लगाकर देखिए।\n\n"
     "इस पर नज़र रखिए: गेज पर प्रेशर ठीक पर साइकिल के दौरान गिरता हुआ (लीकेज या "
     "पतली पाइप), और ऐसा सिलेंडर जो सिर्फ़ तब धीमा होता है जब दूसरी मशीनें चल "
     "रही हों।"),

    ("Pneumatic", "Common Pneumatic Faults - quick checks",
     "CYLINDER DOES NOT MOVE: press the valve manual override. If it moves, the "
     "fault is electrical (no 24V / PLC output / coil). If it does not, the "
     "fault is pneumatic (no air, spool stuck, choked line).\n\n"
     "CYLINDER SLOW: speed control choked, silencer choked, low pressure, or "
     "worn seal.\n\n"
     "CYLINDER DOES NOT REACH END: low pressure, mechanical jam, or the part is "
     "not seated correctly.\n\n"
     "SIGNAL NOT COMING: reed switch position shifted, cable broken, or the "
     "cylinder truly did not reach the end.",
     "सिलेंडर हिलता ही नहीं: वाल्व का मैनुअल ओवरराइड दबाइए। हिल गया तो दिक्कत "
     "इलेक्ट्रिकल है (24V नहीं / PLC आउटपुट नहीं / कॉइल)। नहीं हिला तो दिक्कत "
     "न्यूमैटिक है (हवा नहीं, स्पूल अटका, लाइन चोक)।\n\n"
     "सिलेंडर धीमा: स्पीड कंट्रोल चोक, साइलेंसर चोक, प्रेशर कम, या सील घिसी "
     "हुई।\n\n"
     "सिलेंडर एंड तक नहीं जाता: प्रेशर कम, मैकेनिकल जाम, या पार्ट ठीक से बैठा "
     "नहीं है।\n\n"
     "सिग्नल नहीं आ रहा: रीड स्विच अपनी जगह से खिसक गया, केबल टूटा, या सिलेंडर "
     "सच में एंड तक पहुँचा ही नहीं।"),

    # ── Hydraulic ───────────────────────────────────────────────────────
    ("Hydraulic", "What is a Hydraulic System?",
     "A hydraulic system uses OIL under pressure to do work. Oil does not "
     "compress, so hydraulics gives very high force and can hold a position "
     "steadily - which air cannot.\n\n"
     "The path: tank -> pump (driven by motor) -> pressure relief valve -> "
     "directional valve -> cylinder, and back to tank through the return "
     "filter.\n\n"
     "Working pressure is far higher than air - often 50 to 200 bar. That is "
     "why a hydraulic leak is a safety matter, not just a housekeeping one: a "
     "pinhole jet can cut skin.\n\n"
     "COMMON FAULTS: low oil level, hot oil, contaminated oil, choked filter, "
     "air in the system.",
     "हाइड्रोलिक सिस्टम दबाव वाले तेल से काम करता है। तेल दबता नहीं, इसलिए "
     "हाइड्रोलिक बहुत ज़्यादा फ़ोर्स देता है और पोज़िशन को स्थिर रोक सकता है — "
     "जो हवा नहीं कर सकती।\n\n"
     "रास्ता: टैंक → पंप (मोटर से) → प्रेशर रिलीफ़ वाल्व → डायरेक्शनल वाल्व → "
     "सिलेंडर, और रिटर्न फ़िल्टर से होकर वापस टैंक में।\n\n"
     "इसका प्रेशर हवा से कहीं ज़्यादा होता है — अक्सर 50 से 200 बार। इसीलिए "
     "हाइड्रोलिक लीकेज सिर्फ़ सफ़ाई का नहीं, सेफ़्टी का मामला है: पिनहोल से "
     "निकलती पतली धार चमड़ी काट सकती है।\n\n"
     "आम दिक्कतें: तेल का लेवल कम, तेल गर्म, तेल गंदा, फ़िल्टर चोक, सिस्टम में "
     "हवा।"),

    ("Hydraulic", "Hydraulic Pump",
     "The pump is driven by the motor and pushes oil into the system. It "
     "creates FLOW; pressure is created by the resistance the flow meets, and "
     "is limited by the pressure relief valve setting.\n\n"
     "Common types on machines: gear pump (simple, fixed flow) and vane or "
     "piston pump (can be variable).\n\n"
     "COMMON FAULTS: noisy pump usually means it is sucking air or starving - "
     "check oil level, suction strainer and suction line joints. Also: coupling "
     "worn, wrong rotation direction after a motor rewind, and internal wear "
     "which shows up as low pressure and hot oil.",
     "पंप मोटर से चलता है और तेल को सिस्टम में भेजता है। यह फ़्लो बनाता है; "
     "प्रेशर उस रुकावट से बनता है जो फ़्लो को मिलती है, और प्रेशर रिलीफ़ वाल्व "
     "की सेटिंग से सीमित होता है।\n\n"
     "मशीनों पर आम टाइप: गियर पंप (सीधा, फ़िक्स्ड फ़्लो) और वेन या पिस्टन पंप "
     "(वेरिएबल हो सकता है)।\n\n"
     "आम दिक्कतें: पंप का शोर आम तौर पर मतलब है कि वह हवा खींच रहा है या तेल कम "
     "पड़ रहा है — तेल का लेवल, सक्शन स्ट्रेनर और सक्शन लाइन के जोड़ देखिए। और: "
     "कपलिंग घिसा हुआ, मोटर रिवाइंड के बाद घूमने की दिशा गलत, और अंदर की घिसावट "
     "— जो कम प्रेशर और गर्म तेल के रूप में दिखती है।"),

    ("Hydraulic", "Hydraulic Cylinder",
     "Same idea as a pneumatic cylinder, but with oil - so it gives far more "
     "force and holds position without springiness.\n\n"
     "Because pressure is high, seals matter much more. A worn piston seal lets "
     "oil pass INSIDE the cylinder, so the cylinder becomes slow or drifts down "
     "under load, even though there is no visible leak outside.\n\n"
     "COMMON FAULTS: rod seal leaking (oil on the rod), piston seal passing "
     "(loss of force, drifting), rod scored or rusted which then cuts the seal "
     "again, and air trapped inside causing jerky motion.",
     "सोच न्यूमैटिक सिलेंडर जैसी ही है, पर तेल के साथ — इसलिए यह कहीं ज़्यादा "
     "फ़ोर्स देता है और बिना स्प्रिंगीपन के पोज़िशन रोकता है।\n\n"
     "प्रेशर ज़्यादा होने की वजह से सील का महत्व बहुत बढ़ जाता है। घिसा हुआ "
     "पिस्टन सील तेल को सिलेंडर के अंदर ही निकल जाने देता है, इसलिए सिलेंडर धीमा "
     "हो जाता है या लोड में नीचे खिसकता है — जबकि बाहर कोई लीकेज दिखती ही नहीं।\n\n"
     "आम दिक्कतें: रॉड सील से लीकेज (रॉड पर तेल), पिस्टन सील का पास होना (फ़ोर्स "
     "कम, खिसकना), रॉड पर खरोंच या जंग जो फिर से सील काट देती है, और अंदर फँसी "
     "हवा से झटके वाली मूवमेंट।"),

    ("Hydraulic", "Hydraulic Oil and Filter",
     "Most hydraulic failures are oil failures. Three things decide oil "
     "health:\n\n"
     "LEVEL - check with the machine idle and cylinders home, otherwise the "
     "reading is wrong.\n"
     "CLEANLINESS - dirt is the number one killer of valves and pumps. Change "
     "filters on schedule, not only when they look dirty.\n"
     "TEMPERATURE - hot oil becomes thin, loses film strength and ages fast. If "
     "oil runs hot, look for a relief valve dumping continuously or a choked "
     "cooler.\n\n"
     "Milky oil means water has entered. Dark, burnt-smelling oil means it has "
     "been overheated. Both need attention, not top-up.",
     "ज़्यादातर हाइड्रोलिक फ़ेलियर असल में तेल की फ़ेलियर होती है। तेल की सेहत "
     "तीन चीज़ों से तय होती है:\n\n"
     "लेवल — मशीन बंद और सिलेंडर होम पोज़िशन में हों तभी देखें, वरना रीडिंग गलत "
     "आती है।\n"
     "सफ़ाई — गंदगी वाल्व और पंप की सबसे बड़ी दुश्मन है। फ़िल्टर शेड्यूल पर "
     "बदलें, सिर्फ़ गंदे दिखने पर नहीं।\n"
     "तापमान — गर्म तेल पतला हो जाता है, फ़िल्म स्ट्रेंथ खोता है और जल्दी पुराना "
     "पड़ता है। तेल गर्म चल रहा हो तो देखें कि रिलीफ़ वाल्व लगातार तो नहीं छोड़ "
     "रहा, या कूलर चोक तो नहीं।\n\n"
     "दूधिया तेल मतलब पानी चला गया है। काला और जली हुई गंध वाला तेल मतलब "
     "ज़्यादा गर्म हुआ है। दोनों में टॉप-अप नहीं, ध्यान चाहिए।"),

    ("Hydraulic", "Common Hydraulic Faults - quick checks",
     "NO PRESSURE: relief valve set too low or stuck open, pump worn, suction "
     "starved, or motor turning the wrong way.\n\n"
     "PRESSURE OK BUT NO MOVEMENT: directional valve not shifting (check 24V "
     "and manual override), or a line valve closed.\n\n"
     "SLOW OR WEAK: internal leakage past worn seals, oil too hot and thin, or "
     "flow control set low.\n\n"
     "NOISY: air in the suction line, low oil, choked strainer.\n\n"
     "CYLINDER DRIFTS DOWN: piston seal passing or a pilot-operated check valve "
     "leaking. Never work under a drifting cylinder - support it mechanically.",
     "प्रेशर नहीं बन रहा: रिलीफ़ वाल्व कम सेट या खुला अटका, पंप घिसा हुआ, सक्शन "
     "में तेल कम, या मोटर उल्टा घूम रहा है।\n\n"
     "प्रेशर ठीक पर मूवमेंट नहीं: डायरेक्शनल वाल्व शिफ़्ट नहीं हो रहा (24V और "
     "मैनुअल ओवरराइड देखें), या लाइन का कोई वाल्व बंद है।\n\n"
     "धीमा या कमज़ोर: घिसी सील से अंदर ही लीकेज, तेल बहुत गर्म और पतला, या फ़्लो "
     "कंट्रोल कम सेट।\n\n"
     "शोर: सक्शन लाइन में हवा, तेल कम, स्ट्रेनर चोक।\n\n"
     "सिलेंडर नीचे खिसकता है: पिस्टन सील पास कर रहा है या पायलट-ऑपरेटेड चेक "
     "वाल्व लीक कर रहा है। खिसकते सिलेंडर के नीचे कभी काम मत कीजिए — उसे "
     "मैकेनिकली सपोर्ट कीजिए।"),

    # ── Electrical ──────────────────────────────────────────────────────
    ("Electrical", "Induction Motor",
     "The three-phase induction motor is the workhorse of the plant - it drives "
     "pumps, conveyors, spindles and fans.\n\n"
     "The nameplate tells you what it should draw: kW/HP, voltage, full load "
     "current (FLA) and RPM. Comparing the measured current against FLA is the "
     "quickest health check there is.\n\n"
     "COMMON FAULTS: overload tripping (mechanical jam, bearing seized, "
     "under-voltage, single phasing), overheating (blocked cooling fan, "
     "overload, high ambient), noisy bearings, insulation failure due to "
     "moisture - check with a megger before re-energising a suspect motor.",
     "थ्री-फ़ेज़ इंडक्शन मोटर प्लांट का सबसे मेहनती हिस्सा है — पंप, कन्वेयर, "
     "स्पिंडल और फ़ैन सब इसी से चलते हैं।\n\n"
     "नेमप्लेट बताती है कि उसे कितना लेना चाहिए: kW/HP, वोल्टेज, फ़ुल लोड करंट "
     "(FLA) और RPM। नापा हुआ करंट FLA से मिलाना सबसे तेज़ सेहत-जाँच है।\n\n"
     "आम दिक्कतें: ओवरलोड ट्रिप (मैकेनिकल जाम, बेयरिंग जाम, वोल्टेज कम, सिंगल "
     "फ़ेज़िंग), ज़्यादा गर्म होना (कूलिंग फ़ैन बंद, ओवरलोड, आसपास गर्मी), बेयरिंग "
     "का शोर, नमी से इंसुलेशन फ़ेल — शक वाले मोटर को दोबारा सप्लाई देने से पहले "
     "मेगर से जाँच कीजिए।"),

    ("Electrical", "VFD (Variable Frequency Drive)",
     "A VFD controls motor speed by changing the FREQUENCY supplied to it. It "
     "also gives soft start, which reduces mechanical shock and starting "
     "current.\n\n"
     "It shows fault codes on its display - always note the code BEFORE "
     "resetting, otherwise the evidence is gone.\n\n"
     "COMMON FAULTS: OVER CURRENT (mechanical load, acceleration time too "
     "short, motor cable fault), OVER VOLTAGE (deceleration too fast - needs "
     "longer ramp or a braking resistor), OVER HEAT (cooling fan or filter "
     "choked, panel too hot), UNDER VOLTAGE (incoming supply dip). Never "
     "repeatedly reset a tripping drive without finding the cause.",
     "VFD मोटर की स्पीड उसकी फ़्रीक्वेंसी बदलकर कंट्रोल करता है। यह सॉफ़्ट "
     "स्टार्ट भी देता है, जिससे मैकेनिकल झटका और स्टार्टिंग करंट दोनों कम होते "
     "हैं।\n\n"
     "यह अपने डिस्प्ले पर फ़ॉल्ट कोड दिखाता है — रीसेट करने से पहले कोड हमेशा "
     "नोट कर लीजिए, वरना सबूत चला जाता है।\n\n"
     "आम दिक्कतें: OVER CURRENT (मैकेनिकल लोड, एक्सेलेरेशन टाइम बहुत कम, मोटर "
     "केबल में फ़ॉल्ट), OVER VOLTAGE (डिसेलेरेशन बहुत तेज़ — लंबा रैंप या ब्रेकिंग "
     "रेज़िस्टर चाहिए), OVER HEAT (कूलिंग फ़ैन या फ़िल्टर चोक, पैनल गर्म), UNDER "
     "VOLTAGE (आने वाली सप्लाई गिर रही है)। ट्रिप होते ड्राइव को बिना वजह ढूँढे "
     "बार-बार रीसेट मत कीजिए।"),

    ("Electrical", "Relay",
     "A relay is an electrically operated switch: a small coil current controls "
     "a larger or separate circuit. It is also used to isolate the PLC from "
     "field voltages.\n\n"
     "Contacts are NO (normally open) and NC (normally closed). Coil voltage is "
     "printed on the body - 24V DC is the common one on machines.\n\n"
     "COMMON FAULTS: contact pitted or welded from switching an inductive load, "
     "coil burnt, relay loose in its base, and the flyback diode missing on a "
     "DC coil (which slowly damages the driving output).",
     "रिले एक इलेक्ट्रिकली चलने वाला स्विच है: कॉइल का छोटा करंट एक बड़े या अलग "
     "सर्किट को कंट्रोल करता है। इससे PLC को फ़ील्ड के वोल्टेज से अलग रखने का "
     "काम भी लिया जाता है।\n\n"
     "कॉन्टैक्ट NO (नॉर्मली ओपन) और NC (नॉर्मली क्लोज़्ड) होते हैं। कॉइल का "
     "वोल्टेज बॉडी पर लिखा होता है — मशीनों पर आम तौर पर 24V DC।\n\n"
     "आम दिक्कतें: इंडक्टिव लोड स्विच करने से कॉन्टैक्ट का गड्ढा पड़ जाना या "
     "चिपक जाना, कॉइल जल जाना, रिले अपने बेस में ढीला, और DC कॉइल पर फ़्लाईबैक "
     "डायोड न होना (जो धीरे-धीरे चलाने वाले आउटपुट को ख़राब करता है)।"),

    ("Electrical", "Contactor and Overload Relay",
     "A contactor is a heavy-duty relay used to switch motors. An OVERLOAD "
     "RELAY sits with it and trips if the motor draws more current than set for "
     "too long.\n\n"
     "The overload must be set to the motor nameplate FLA - not higher 'so it "
     "stops tripping'. Raising the setting to stop nuisance tripping is how "
     "motors get burnt.\n\n"
     "COMMON FAULTS: contact tips burnt or welded (motor keeps running after "
     "stop - dangerous), coil burnt, chattering due to low control voltage or "
     "loose wiring, overload set wrong, and single phasing which the overload "
     "may not always catch.",
     "कॉन्टैक्टर एक हेवी-ड्यूटी रिले है जो मोटर को स्विच करता है। उसके साथ "
     "ओवरलोड रिले लगता है, जो मोटर के सेट से ज़्यादा करंट लेने पर (कुछ देर तक) "
     "ट्रिप कर देता है।\n\n"
     "ओवरलोड को मोटर के नेमप्लेट FLA पर ही सेट करना चाहिए — 'बार-बार ट्रिप न "
     "करे' इसलिए ज़्यादा पर नहीं। सेटिंग बढ़ाकर ट्रिप रोकना ही वह तरीक़ा है जिससे "
     "मोटर जलते हैं।\n\n"
     "आम दिक्कतें: कॉन्टैक्ट टिप जल जाना या चिपक जाना (स्टॉप के बाद भी मोटर चलता "
     "रहे — ख़तरनाक), कॉइल जलना, कंट्रोल वोल्टेज कम या वायरिंग ढीली होने से "
     "खड़खड़ाना, ओवरलोड गलत सेट, और सिंगल फ़ेज़िंग जिसे ओवरलोड हमेशा नहीं पकड़ता।"),

    ("Electrical", "MCB and MCCB",
     "These are the protection devices in the panel.\n\n"
     "MCB - small breaker for control and lighting circuits.\n"
     "MCCB - larger breaker for motors and main incomers, usually adjustable.\n\n"
     "They protect against OVERLOAD (slow, thermal) and SHORT CIRCUIT (instant, "
     "magnetic).\n\n"
     "A breaker that trips is doing its job - it is telling you something. "
     "Never bypass or hold one closed. If it trips again immediately, there is "
     "a dead short; if it trips after some minutes, it is an overload.\n\n"
     "COMMON FAULTS: repeated tripping (find the cause), loose terminals "
     "causing heating, and a breaker that will not reset because the fault is "
     "still present.",
     "ये पैनल के सुरक्षा वाले डिवाइस हैं।\n\n"
     "MCB — कंट्रोल और लाइटिंग सर्किट के लिए छोटा ब्रेकर।\n"
     "MCCB — मोटर और मेन इनकमर के लिए बड़ा ब्रेकर, आम तौर पर एडजस्टेबल।\n\n"
     "ये ओवरलोड (धीरे, थर्मल) और शॉर्ट सर्किट (तुरंत, मैग्नेटिक) दोनों से बचाते "
     "हैं।\n\n"
     "ट्रिप होता ब्रेकर अपना काम कर रहा है — वह आपको कुछ बता रहा है। उसे कभी "
     "बायपास मत कीजिए और न ही ज़बरदस्ती बंद पकड़िए। तुरंत दोबारा ट्रिप करे तो "
     "सीधा शॉर्ट है; कुछ मिनट बाद करे तो ओवरलोड है।\n\n"
     "आम दिक्कतें: बार-बार ट्रिप (वजह ढूँढें), टर्मिनल ढीले होने से गर्मी, और "
     "ब्रेकर का रीसेट न होना क्योंकि फ़ॉल्ट अभी मौजूद है।"),

    ("Electrical", "SMPS (24V Power Supply)",
     "The SMPS converts 230V AC into the 24V DC that the PLC, sensors, HMI and "
     "solenoid coils run on. If it is weak, MANY unrelated things start "
     "misbehaving at once - that pattern is a strong clue.\n\n"
     "Always measure the actual 24V under load, not with everything switched "
     "off.\n\n"
     "COMMON FAULTS: output sagging under load (undersized or ageing SMPS), "
     "output capacitors dried so the DC has ripple, overload from a shorted "
     "sensor cable, and heat because the panel fan or filter is choked.",
     "SMPS 230V AC को 24V DC में बदलता है, जिस पर PLC, सेंसर, HMI और सोलेनॉइड "
     "कॉइल चलते हैं। यह कमज़ोर हो जाए तो एक साथ बहुत सी अलग-अलग चीज़ें अजीब हरकत "
     "करने लगती हैं — यही पैटर्न बड़ा संकेत है।\n\n"
     "24V हमेशा लोड के साथ नापिए, सब बंद करके नहीं।\n\n"
     "आम दिक्कतें: लोड पर आउटपुट गिर जाना (छोटा या पुराना SMPS), आउटपुट "
     "कैपेसिटर सूख जाने से DC में रिपल, किसी शॉर्ट सेंसर केबल से ओवरलोड, और "
     "पैनल का फ़ैन/फ़िल्टर चोक होने से गर्मी।"),

    ("Electrical", "Transformer",
     "A transformer changes voltage - for example 415V to 230V for control, or "
     "to 110V for safety circuits. It also isolates the control circuit from "
     "the main supply.\n\n"
     "It should hum lightly, not buzz loudly or smell hot.\n\n"
     "COMMON FAULTS: overheating from overload or blocked ventilation, loud "
     "buzzing from loose laminations or loose terminals, burnt smell and "
     "discoloured windings (replace, do not re-energise), and low output "
     "voltage due to a loose tap connection.",
     "ट्रांसफ़ॉर्मर वोल्टेज बदलता है — जैसे कंट्रोल के लिए 415V से 230V, या "
     "सेफ़्टी सर्किट के लिए 110V। यह कंट्रोल सर्किट को मेन सप्लाई से अलग भी रखता "
     "है।\n\n"
     "इसकी हल्की गुनगुनाहट सामान्य है, पर तेज़ भिनभिनाहट या गर्म गंध नहीं।\n\n"
     "आम दिक्कतें: ओवरलोड या हवा रुक जाने से ज़्यादा गर्म होना, लैमिनेशन या "
     "टर्मिनल ढीले होने से तेज़ आवाज़, जली हुई गंध और रंग बदली वाइंडिंग (बदल "
     "दीजिए, दोबारा सप्लाई मत दीजिए), और टैप कनेक्शन ढीला होने से आउटपुट वोल्टेज "
     "कम।"),

    ("Electrical", "Earthing",
     "Earthing gives fault current a safe path to ground. It is what keeps a "
     "person alive when insulation fails, and it is also what keeps sensor and "
     "communication signals clean.\n\n"
     "Every panel, motor body and machine frame must be properly bonded. Cable "
     "SCREENS should be earthed at one end only - earthing both ends can create "
     "a loop that injects noise.\n\n"
     "COMMON FAULTS: loose or painted-over earth connections, corroded earth "
     "pit, earth removed during a modification and never restored, and "
     "unexplained sensor or communication faults that are actually an earthing "
     "problem.",
     "अर्थिंग फ़ॉल्ट करंट को ज़मीन तक एक सुरक्षित रास्ता देती है। इंसुलेशन फ़ेल "
     "होने पर इंसान की जान यही बचाती है, और सेंसर तथा कम्युनिकेशन के सिग्नल भी "
     "यही साफ़ रखती है।\n\n"
     "हर पैनल, मोटर की बॉडी और मशीन का फ़्रेम ठीक से बॉन्ड होना चाहिए। केबल की "
     "शील्ड सिर्फ़ एक सिरे पर अर्थ होनी चाहिए — दोनों सिरे अर्थ करने से लूप बनकर "
     "नॉइज़ आ सकता है।\n\n"
     "आम दिक्कतें: अर्थ कनेक्शन ढीला या उस पर पेंट, अर्थ पिट में जंग, किसी "
     "मॉडिफ़िकेशन में अर्थ खोलकर वापस न लगाना, और सेंसर या कम्युनिकेशन के ऐसे "
     "फ़ॉल्ट जो असल में अर्थिंग की दिक्कत होते हैं।"),

    # ── Control (PLC / HMI) ─────────────────────────────────────────────
    ("Control", "What is a PLC?",
     "A PLC (Programmable Logic Controller) is the industrial computer that "
     "runs the machine. It reads INPUTS (sensors, switches), runs the program, "
     "and drives OUTPUTS (solenoids, contactors, lamps).\n\n"
     "It works in a SCAN CYCLE, repeated continuously and very fast: read all "
     "inputs -> solve the program -> write all outputs.\n\n"
     "Because it reads all inputs at the START of the scan, a signal shorter "
     "than one scan can be missed entirely - which is exactly why a very fast "
     "cylinder can 'skip' its reed switch.\n\n"
     "The PLC also has a RUN/STOP mode and battery-backed memory for retained "
     "data.",
     "PLC (Programmable Logic Controller) वह इंडस्ट्रियल कंप्यूटर है जो मशीन "
     "चलाता है। यह इनपुट पढ़ता है (सेंसर, स्विच), प्रोग्राम चलाता है, और आउटपुट "
     "चलाता है (सोलेनॉइड, कॉन्टैक्टर, लैंप)।\n\n"
     "यह स्कैन साइकिल में काम करता है, जो लगातार और बहुत तेज़ दोहराया जाता है: "
     "सारे इनपुट पढ़ो → प्रोग्राम हल करो → सारे आउटपुट लिखो।\n\n"
     "क्योंकि यह सारे इनपुट स्कैन के शुरू में पढ़ता है, इसलिए एक स्कैन से छोटा "
     "सिग्नल पूरी तरह छूट सकता है — और इसी वजह से बहुत तेज़ सिलेंडर अपना रीड "
     "स्विच 'स्किप' कर जाता है।\n\n"
     "PLC में RUN/STOP मोड भी होता है और बैटरी से बची हुई मेमोरी भी, रिटेन "
     "डेटा के लिए।"),

    ("Control", "PLC Input and Output",
     "INPUT (X / I) - signals coming INTO the PLC from sensors and switches.\n"
     "OUTPUT (Y / Q) - signals going OUT to solenoids, contactors and lamps.\n\n"
     "Digital means ON/OFF. Analog means a value - 4-20 mA or 0-10 V - used for "
     "pressure, temperature and position.\n\n"
     "Each I/O point has an LED on the module. That LED is your fastest "
     "diagnostic tool:\n\n"
     "  Sensor LED ON but PLC input LED OFF -> wiring, common, or wrong "
     "PNP/NPN.\n"
     "  PLC output LED ON but device dead -> coil, fuse or field wiring.\n"
     "  Output LED OFF when it should be ON -> the program is not commanding "
     "it; look for an interlock, not a hardware fault.",
     "INPUT (X / I) — सेंसर और स्विच से PLC के अंदर आने वाले सिग्नल।\n"
     "OUTPUT (Y / Q) — सोलेनॉइड, कॉन्टैक्टर और लैंप की तरफ़ बाहर जाने वाले "
     "सिग्नल।\n\n"
     "डिजिटल मतलब ON/OFF। एनालॉग मतलब एक वैल्यू — 4–20 mA या 0–10 V — जो प्रेशर, "
     "तापमान और पोज़िशन के लिए इस्तेमाल होती है।\n\n"
     "हर I/O पॉइंट पर मॉड्यूल पर एक LED होती है। वही LED आपका सबसे तेज़ जाँच का "
     "औज़ार है:\n\n"
     "  सेंसर की LED ON पर PLC इनपुट की LED OFF → वायरिंग, कॉमन, या गलत "
     "PNP/NPN।\n"
     "  PLC आउटपुट की LED ON पर डिवाइस बंद → कॉइल, फ़्यूज़ या फ़ील्ड वायरिंग।\n"
     "  आउटपुट LED OFF जबकि ON होनी चाहिए → प्रोग्राम ही उसे कमांड नहीं कर रहा; "
     "हार्डवेयर नहीं, कोई इंटरलॉक ढूँढिए।"),

    ("Control", "Ladder Logic - the basics",
     "Ladder logic is drawn like an electrical circuit, which is why "
     "maintenance people read it easily.\n\n"
     "  --| |--  normally open contact: passes when the bit is ON\n"
     "  --|/|--  normally closed contact: passes when the bit is OFF\n"
     "  --( )--  output coil\n\n"
     "Contacts in a row = AND. Contacts in parallel branches = OR.\n\n"
     "SET / RESET (latch) holds a bit ON until something resets it - this is "
     "why an output can stay ON even after its condition has gone.\n\n"
     "When reading a fault: find the output coil that is not coming ON, then "
     "work LEFT along its rung to find which contact is blocking it. That one "
     "habit solves most control faults.",
     "लैडर लॉजिक इलेक्ट्रिकल सर्किट की तरह बनी होती है, इसीलिए मेंटेनेंस वाले "
     "इसे आसानी से पढ़ लेते हैं।\n\n"
     "  --| |--  नॉर्मली ओपन कॉन्टैक्ट: बिट ON होने पर करंट जाता है\n"
     "  --|/|--  नॉर्मली क्लोज़्ड कॉन्टैक्ट: बिट OFF होने पर करंट जाता है\n"
     "  --( )--  आउटपुट कॉइल\n\n"
     "एक लाइन में कॉन्टैक्ट = AND। अलग-अलग ब्रांच में कॉन्टैक्ट = OR।\n\n"
     "SET / RESET (लैच) बिट को ON पकड़कर रखता है जब तक कोई उसे रीसेट न करे — "
     "इसीलिए कभी-कभी कंडीशन हटने के बाद भी आउटपुट ON रह जाता है।\n\n"
     "फ़ॉल्ट देखते वक़्त: वह आउटपुट कॉइल ढूँढिए जो ON नहीं हो रही, फिर उसी "
     "लाइन (rung) पर बाएँ चलिए और देखिए कौन सा कॉन्टैक्ट रोक रहा है। यही एक आदत ज़्यादातर "
     "कंट्रोल के फ़ॉल्ट हल कर देती है।"),

    ("Control", "HMI (Human Machine Interface)",
     "The HMI is the touch screen on the machine. It shows status, alarms and "
     "counters, and lets the operator give commands and change recipe or "
     "setting values.\n\n"
     "The HMI does not control anything by itself - it only reads and writes "
     "PLC memory. So an HMI alarm is really a PLC bit; if the screen shows a "
     "fault, the truth is in the PLC.\n\n"
     "COMMON FAULTS: no communication with the PLC (cable, IP address, station "
     "number), touch not responding or offset (needs calibration), backlight "
     "dim or dead, and a blank screen which is usually a 24V supply problem.",
     "HMI मशीन पर लगा टच स्क्रीन है। यह स्टेटस, अलार्म और काउंटर दिखाता है, और "
     "ऑपरेटर को कमांड देने तथा रेसिपी/सेटिंग की वैल्यू बदलने देता है।\n\n"
     "HMI ख़ुद कुछ कंट्रोल नहीं करता — यह सिर्फ़ PLC की मेमोरी पढ़ता और लिखता है। "
     "इसलिए HMI का अलार्म असल में PLC का एक बिट ही है; स्क्रीन पर फ़ॉल्ट दिखे तो "
     "सच PLC में है।\n\n"
     "आम दिक्कतें: PLC से कम्युनिकेशन न होना (केबल, IP एड्रेस, स्टेशन नंबर), टच "
     "का काम न करना या जगह से हटकर लगना (कैलिब्रेशन चाहिए), बैकलाइट धीमी या "
     "बंद, और ख़ाली स्क्रीन — जो आम तौर पर 24V सप्लाई की दिक्कत होती है।"),

    ("Control", "Industrial Communication",
     "Machines talk to each other and to systems like this MES over industrial "
     "networks - usually Ethernet based.\n\n"
     "On our ANDON the PLCs are read over MC protocol (SLMP) on Ethernet. The "
     "PLC listens on a set IP and PORT, and a device connects to read or write "
     "its memory (M bits, D registers).\n\n"
     "One important limit: many PLC Ethernet settings allow only a LIMITED "
     "number of simultaneous connections - sometimes only one. If two systems "
     "try to read the same port, one of them gets refused, and the fault looks "
     "random.\n\n"
     "COMMON FAULTS: wrong IP or port, cable or switch fault, connection limit "
     "reached, and PLC in STOP mode.",
     "मशीनें आपस में और इस MES जैसे सिस्टम से इंडस्ट्रियल नेटवर्क पर बात करती "
     "हैं — आम तौर पर ईथरनेट पर।\n\n"
     "हमारे ANDON में PLC को ईथरनेट पर MC प्रोटोकॉल (SLMP) से पढ़ा जाता है। PLC "
     "एक तय IP और पोर्ट पर सुनता है, और कोई डिवाइस उससे जुड़कर उसकी मेमोरी (M "
     "बिट, D रजिस्टर) पढ़ता या लिखता है।\n\n"
     "एक ज़रूरी सीमा: बहुत से PLC की ईथरनेट सेटिंग में एक साथ सीमित ही कनेक्शन "
     "बन सकते हैं — कभी-कभी सिर्फ़ एक। दो सिस्टम एक ही पोर्ट पढ़ने की कोशिश करें "
     "तो एक को मना कर दिया जाता है, और फ़ॉल्ट बिल्कुल रैंडम लगता है।\n\n"
     "आम दिक्कतें: गलत IP या पोर्ट, केबल या स्विच की दिक्कत, कनेक्शन की सीमा भर "
     "जाना, और PLC का STOP मोड में होना।"),

    ("Control", "Safety Relay and Emergency Stop",
     "Safety circuits are deliberately built so that ANY failure stops the "
     "machine. That is why E-stops and guard switches use NORMALLY CLOSED "
     "contacts - a cut wire or a loose terminal opens the circuit and trips the "
     "machine, exactly as a real E-stop would.\n\n"
     "A safety relay monitors these contacts, usually on two channels, and only "
     "allows the machine to run when both agree. It normally needs a deliberate "
     "RESET after a trip - it must never restart on its own.\n\n"
     "NEVER bypass, jumper or defeat a safety device to keep production "
     "running. If a safety circuit trips repeatedly, find the cause and record "
     "it.",
     "सेफ़्टी सर्किट जान-बूझकर ऐसे बनाए जाते हैं कि कोई भी ख़राबी मशीन को रोक दे। "
     "इसीलिए E-stop और गार्ड स्विच में नॉर्मली क्लोज़्ड कॉन्टैक्ट लगते हैं — तार "
     "कटने या टर्मिनल ढीला होने पर सर्किट खुल जाता है और मशीन रुक जाती है, "
     "बिल्कुल वैसे जैसे असली E-stop पर होती।\n\n"
     "सेफ़्टी रिले इन कॉन्टैक्ट को देखता रहता है, आम तौर पर दो चैनल पर, और तभी "
     "चलने देता है जब दोनों एक बात कहें। ट्रिप के बाद इसे जान-बूझकर रीसेट करना "
     "पड़ता है — यह ख़ुद से कभी चालू नहीं होना चाहिए।\n\n"
     "प्रोडक्शन चालू रखने के लिए किसी सेफ़्टी डिवाइस को कभी बायपास, जंपर या बंद "
     "मत कीजिए। सेफ़्टी सर्किट बार-बार ट्रिप हो तो वजह ढूँढिए और लिखिए।"),

    # ── Mechanical ──────────────────────────────────────────────────────
    ("Mechanical", "Bearing",
     "A bearing lets a shaft turn with little friction and carries the load.\n\n"
     "Most bearing failures are not the bearing's fault - they come from wrong "
     "fitting, wrong lubrication, contamination or misalignment.\n\n"
     "Warning signs: noise (growling or a regular click), heat, and vibration. "
     "A bearing that has started to sound bad will not recover; plan its "
     "replacement instead of waiting for seizure.\n\n"
     "COMMON FAULTS: over-greasing (as damaging as under-greasing), hammering "
     "the bearing on during fitting, wrong shaft or housing fit, water/dust "
     "entry due to a damaged seal, and misalignment from a worn coupling.",
     "बेयरिंग शाफ़्ट को कम घिसावट में घूमने देता है और लोड उठाता है।\n\n"
     "ज़्यादातर बेयरिंग फ़ेलियर बेयरिंग की गलती होती ही नहीं — वह गलत फ़िटिंग, "
     "गलत लुब्रिकेशन, गंदगी या मिसएलाइनमेंट से आती है।\n\n"
     "चेतावनी के संकेत: आवाज़ (गुर्राहट या लगातार क्लिक), गर्मी, और वाइब्रेशन। "
     "जो बेयरिंग आवाज़ देना शुरू कर दे वह ठीक नहीं होती; जाम होने का इंतज़ार करने "
     "के बजाय उसका रिप्लेसमेंट प्लान कीजिए।\n\n"
     "आम दिक्कतें: ज़्यादा ग्रीस (कम ग्रीस जितना ही नुकसानदेह), फ़िटिंग के वक़्त "
     "हथौड़ा मारना, शाफ़्ट या हाउसिंग का गलत फ़िट, सील ख़राब होने से पानी/धूल "
     "जाना, और घिसे कपलिंग से मिसएलाइनमेंट।"),

    ("Mechanical", "Coupling",
     "A coupling joins the motor shaft to the driven shaft and transmits "
     "torque. Flexible couplings (spider/jaw, tyre, pin-bush) also absorb small "
     "misalignment and shock.\n\n"
     "The rubber element is a wear part - it is meant to fail before the "
     "bearings or the shaft do.\n\n"
     "COMMON FAULTS: worn spider or bush causing backlash and knocking, "
     "misalignment which quickly kills bearings on both sides, loose grub screw "
     "or key so the coupling slips, and rubber dust around the guard - which is "
     "an early sign the element is going.",
     "कपलिंग मोटर के शाफ़्ट को चलने वाले शाफ़्ट से जोड़ता है और टॉर्क पहुँचाता है। "
     "फ़्लेक्सिबल कपलिंग (स्पाइडर/जॉ, टायर, पिन-बुश) थोड़ी मिसएलाइनमेंट और झटका "
     "भी सोख लेती है।\n\n"
     "रबर वाला एलिमेंट घिसने वाला पार्ट है — वह जान-बूझकर बेयरिंग या शाफ़्ट से "
     "पहले फ़ेल होने के लिए बनाया जाता है।\n\n"
     "आम दिक्कतें: स्पाइडर या बुश घिस जाने से बैकलैश और ठोक, मिसएलाइनमेंट जो "
     "दोनों तरफ़ के बेयरिंग जल्दी ख़राब कर देता है, ग्रब स्क्रू या की ढीली होने "
     "से कपलिंग का स्लिप होना, और गार्ड के आसपास रबर का बुरादा — जो एलिमेंट "
     "ख़राब होने का पहला संकेत है।"),

    ("Mechanical", "Gearbox",
     "A gearbox changes speed and increases torque between the motor and the "
     "machine. Its ratio and oil grade are on the nameplate.\n\n"
     "Gearboxes are simple to look after and expensive to replace, so oil and "
     "breather care pays back many times.\n\n"
     "COMMON FAULTS: low or degraded oil, breather choked (pressure builds and "
     "pushes oil out through the seals), oil leak at the output seal, unusual "
     "noise or vibration from worn gears or bearings, and overheating from "
     "overload or wrong oil grade. Metal particles on the drain plug magnet "
     "mean internal wear - investigate, do not just refill.",
     "गियरबॉक्स मोटर और मशीन के बीच स्पीड बदलता है और टॉर्क बढ़ाता है। उसका "
     "रेशियो और ऑइल ग्रेड नेमप्लेट पर लिखा होता है।\n\n"
     "गियरबॉक्स की देखभाल आसान है पर बदलना महँगा, इसलिए तेल और ब्रीदर का ध्यान "
     "कई गुना वापस देता है।\n\n"
     "आम दिक्कतें: तेल कम या ख़राब, ब्रीदर चोक (अंदर प्रेशर बनता है और सील से "
     "तेल बाहर निकलता है), आउटपुट सील पर लीकेज, घिसे गियर या बेयरिंग से अजीब "
     "आवाज़/वाइब्रेशन, और ओवरलोड या गलत ऑइल ग्रेड से ज़्यादा गर्म होना। ड्रेन "
     "प्लग के मैग्नेट पर धातु के कण मतलब अंदर घिसावट — सिर्फ़ तेल भरकर मत "
     "छोड़िए, जाँच कीजिए।"),

    ("Mechanical", "Chain and Belt Drive",
     "Chains and belts transmit power between two shafts.\n\n"
     "TENSION is everything. Too loose and it jumps, slaps and wears the "
     "sprocket teeth; too tight and it destroys the bearings on both shafts.\n\n"
     "Chains need lubrication; most V-belts must be kept clean and dry - oil "
     "makes a belt slip and rot.\n\n"
     "COMMON FAULTS: wrong tension, misaligned pulleys or sprockets (belt runs "
     "to one side, chain wears on one face), worn sprocket teeth becoming "
     "hooked, stretched chain, glazed or cracked belt, and belts of different "
     "ages running as a set - always replace a matched set together.",
     "चेन और बेल्ट दो शाफ़्ट के बीच पावर पहुँचाते हैं।\n\n"
     "टेंशन सब कुछ है। बहुत ढीला हो तो उछलता है, पटकता है और स्प्रॉकेट के दाँत "
     "घिस देता है; बहुत कसा हो तो दोनों शाफ़्ट के बेयरिंग ख़राब कर देता है।\n\n"
     "चेन को लुब्रिकेशन चाहिए; ज़्यादातर V-बेल्ट को साफ़ और सूखा रखना होता है — "
     "तेल लगने से बेल्ट स्लिप करती है और गल जाती है।\n\n"
     "आम दिक्कतें: गलत टेंशन, पुली या स्प्रॉकेट का मिसएलाइनमेंट (बेल्ट एक तरफ़ "
     "चलती है, चेन एक ही फ़ेस पर घिसती है), स्प्रॉकेट के दाँत घिसकर हुक बन जाना, "
     "चेन का खिंच जाना, बेल्ट का चिकना या फटा होना, और अलग-अलग उम्र की बेल्ट एक "
     "सेट में चलाना — मैच्ड सेट हमेशा एक साथ बदलिए।"),

    ("Mechanical", "Lubrication",
     "Lubrication reduces friction, carries away heat and keeps dirt out. Most "
     "'mechanical' failures are really lubrication failures.\n\n"
     "Three rules: the RIGHT lubricant, the RIGHT quantity, at the RIGHT "
     "interval. More is not better - over-greasing a bearing or a motor churns "
     "the grease, heats it and pushes it into the windings.\n\n"
     "Never mix two greases of different types; they can separate and stop "
     "working.\n\n"
     "COMMON FAULTS: missed lubrication points (the ones that are hard to "
     "reach), blocked grease nipple, wrong grade used because it was what was "
     "available, and contamination from a dirty grease gun nozzle.",
     "लुब्रिकेशन घिसावट कम करती है, गर्मी बाहर ले जाती है और गंदगी को अंदर आने "
     "से रोकती है। ज़्यादातर 'मैकेनिकल' फ़ेलियर असल में लुब्रिकेशन की फ़ेलियर होती "
     "है।\n\n"
     "तीन नियम: सही लुब्रिकेंट, सही मात्रा, सही समय पर। ज़्यादा मतलब बेहतर नहीं "
     "— बेयरिंग या मोटर में ज़्यादा ग्रीस भरना उसे मथता है, गर्म करता है और "
     "वाइंडिंग में धकेल देता है।\n\n"
     "दो अलग टाइप की ग्रीस कभी मत मिलाइए; वे अलग होकर काम करना बंद कर सकती "
     "हैं।\n\n"
     "आम दिक्कतें: छूट गए लुब्रिकेशन पॉइंट (जो पहुँच से दूर हैं), ग्रीस निपल बंद, "
     "जो मिल गया वही ग्रेड डाल देना, और गंदे ग्रीस गन नोज़ल से गंदगी जाना।"),

    ("Mechanical", "Fasteners and Torque",
     "A bolt holds by the TENSION created when it is tightened, not by "
     "friction alone. That is why torque matters: too little and it works "
     "loose, too much and it stretches or the thread strips.\n\n"
     "Use a torque wrench where a value is specified, and tighten in the "
     "correct sequence on flanges and covers.\n\n"
     "COMMON FAULTS: bolts loosened by vibration (use lock washers, thread "
     "locker or a locking nut where specified), reused self-locking nuts, "
     "damaged or dirty threads giving false torque, and mixing bolt grades - a "
     "lower grade bolt in a high load place will fail.",
     "बोल्ट उस टेंशन से पकड़ता है जो कसने पर बनता है, सिर्फ़ रुकावट से नहीं। "
     "इसलिए टॉर्क मायने रखता है: कम कसा तो वाइब्रेशन से ढीला हो जाएगा, ज़्यादा "
     "कसा तो खिंच जाएगा या थ्रेड उखड़ जाएगी।\n\n"
     "जहाँ वैल्यू दी गई हो वहाँ टॉर्क रेंच इस्तेमाल कीजिए, और फ़्लैंज या कवर पर "
     "सही क्रम में कसिए।\n\n"
     "आम दिक्कतें: वाइब्रेशन से बोल्ट ढीले होना (जहाँ बताया हो वहाँ लॉक वॉशर, "
     "थ्रेड लॉकर या लॉकिंग नट लगाइए), सेल्फ़-लॉकिंग नट दोबारा इस्तेमाल करना, "
     "थ्रेड ख़राब या गंदी होने से गलत टॉर्क, और बोल्ट के ग्रेड मिलाना — ज़्यादा "
     "लोड वाली जगह पर कम ग्रेड का बोल्ट फ़ेल होगा।"),

    # ── Safety ──────────────────────────────────────────────────────────
    ("Safety", "LOTO - Lock Out Tag Out",
     "LOTO makes sure a machine cannot start while someone is working on it.\n\n"
     "The steps: inform production -> shut down -> isolate every energy source "
     "-> LOCK the isolator and put your TAG on it -> release stored energy "
     "(air, hydraulic pressure, springs, gravity, capacitors) -> TRY to start "
     "the machine to prove it is dead -> then work.\n\n"
     "Remember there is more than one energy source. Switching off the main "
     "supply does not release trapped air pressure or a raised ram.\n\n"
     "One lock, one key, one person. Only the person who fitted the lock "
     "removes it.",
     "LOTO यह पक्का करता है कि जब कोई मशीन पर काम कर रहा हो तो वह चालू न हो "
     "सके।\n\n"
     "क्रम: प्रोडक्शन को बताओ → मशीन बंद करो → हर एनर्जी सोर्स अलग करो → "
     "आइसोलेटर पर ताला लगाओ और अपना टैग लगाओ → जमा एनर्जी छोड़ो (हवा, हाइड्रोलिक "
     "प्रेशर, स्प्रिंग, ग्रैविटी, कैपेसिटर) → मशीन चालू करके देखो कि वह सच में "
     "बंद है → फिर काम करो।\n\n"
     "याद रखिए एनर्जी एक से ज़्यादा जगह होती है। मेन सप्लाई बंद करने से फँसी हुई "
     "हवा या ऊपर उठा हुआ रैम नहीं खुलता।\n\n"
     "एक ताला, एक चाबी, एक आदमी। ताला वही खोलेगा जिसने लगाया था।"),

    ("Safety", "PPE - Personal Protective Equipment",
     "PPE is the LAST line of defence, not the first. The first is removing the "
     "hazard; PPE only protects you when everything else has already failed.\n\n"
     "On maintenance work the usual set is: safety shoes, safety glasses, hand "
     "gloves suited to the job, and ear protection in high-noise areas. Add a "
     "face shield for grinding, and insulated gloves and mat for live "
     "electrical work.\n\n"
     "One warning: gloves that protect against cuts can be dangerous near "
     "rotating parts, where a glove can be caught and pull the hand in. Choose "
     "PPE for the actual job.",
     "PPE बचाव की आख़िरी लाइन है, पहली नहीं। पहली लाइन ख़तरा ही हटा देना है; PPE "
     "तभी बचाता है जब बाकी सब पहले ही फ़ेल हो चुका हो।\n\n"
     "मेंटेनेंस के काम में आम सेट है: सेफ़्टी शूज़, सेफ़्टी ग्लासेज़, काम के हिसाब "
     "से हैंड ग्लव्स, और ज़्यादा शोर वाली जगह पर कान के लिए प्रोटेक्शन। "
     "ग्राइंडिंग पर फ़ेस शील्ड, और लाइव इलेक्ट्रिकल काम पर इंसुलेटेड ग्लव्स और "
     "मैट।\n\n"
     "एक चेतावनी: कट से बचाने वाले ग्लव्स घूमते हुए पार्ट्स के पास ख़तरनाक हो "
     "सकते हैं, जहाँ ग्लव फँसकर हाथ अंदर खींच सकता है। PPE काम देखकर चुनिए।"),

    ("Safety", "Machine Guarding",
     "Guards keep people away from moving parts. Fixed guards are bolted on; "
     "interlocked guards are wired so that opening them stops the machine.\n\n"
     "An interlocked guard is part of the safety circuit - not a "
     "convenience.\n\n"
     "The most dangerous shortcut in any plant is defeating a guard switch with "
     "a spare actuator or a jumper 'just for trials'. It removes the one thing "
     "standing between a person and a moving machine, and it is usually "
     "forgotten in place.\n\n"
     "If a guard interlock keeps tripping, treat it as a fault to be fixed and "
     "recorded - never as something to be bypassed.",
     "गार्ड लोगों को चलते हुए पार्ट्स से दूर रखते हैं। फ़िक्स्ड गार्ड बोल्ट से "
     "कसे होते हैं; इंटरलॉक्ड गार्ड ऐसे जुड़े होते हैं कि खोलते ही मशीन रुक "
     "जाए।\n\n"
     "इंटरलॉक्ड गार्ड सेफ़्टी सर्किट का हिस्सा है — सुविधा की चीज़ नहीं।\n\n"
     "किसी भी प्लांट का सबसे ख़तरनाक शॉर्टकट यही है कि गार्ड स्विच को स्पेयर "
     "एक्चुएटर या जंपर से 'सिर्फ़ ट्रायल के लिए' बायपास कर दिया जाए। वह इंसान और "
     "चलती मशीन के बीच की एकमात्र चीज़ हटा देता है, और आम तौर पर वही लगा रह "
     "जाता है।\n\n"
     "गार्ड इंटरलॉक बार-बार ट्रिप करे तो उसे ठीक करने और लिखने वाली ख़राबी "
     "मानिए — बायपास करने वाली चीज़ कभी नहीं।"),

    # ── Welding ─────────────────────────────────────────────────────────
    ("Welding", "MIG Welding (Metal Inert Gas)",
     "MIG is an arc welding process. A wire is fed continuously from a spool "
     "through the torch. An arc burns between the wire tip and the job, the "
     "wire melts and becomes the filler metal, and a shielding gas flows out "
     "of the nozzle all around the arc.\n\n"
     "The I in MIG means INERT. The gas is pure Argon, or Argon mixed with "
     "Helium. An inert gas does NOT take part in the weld at all - its only "
     "job is to push the air away from the molten metal.\n\n"
     "That is exactly what aluminium, stainless steel and copper need. "
     "Aluminium grabs oxygen from the air the instant it melts and forms an "
     "oxide skin; even a little active gas would leave the weld full of holes "
     "(porosity) and weak.\n\n"
     "COMMON FAULTS: gas bottle empty or flow set too low (bead turns black "
     "and porous), a fan or draught blowing the gas away, wire slipping in the "
     "feed roller or liner, contact tip worn oversize so the arc wanders, "
     "earth clamp loose or clamped on paint.",
     "MIG एक आर्क वेल्डिंग प्रोसेस है। स्पूल से तार (wire) लगातार टॉर्च के "
     "ज़रिये आगे बढ़ता रहता है। तार की नोक और जॉब के बीच आर्क जलता है, तार "
     "पिघल कर भरने वाली धातु बन जाता है, और नोज़ल से निकलती शील्डिंग गैस आर्क "
     "को चारों तरफ़ से ढक लेती है।\n\n"
     "MIG का I मतलब INERT (निष्क्रिय)। गैस होती है शुद्ध Argon, या Argon में "
     "Helium मिला हुआ। निष्क्रिय गैस वेल्ड में हिस्सा बिल्कुल नहीं लेती — "
     "उसका काम सिर्फ़ पिघली धातु से हवा को हटाए रखना है।\n\n"
     "एल्युमिनियम, स्टेनलेस स्टील और कॉपर को यही चाहिए। एल्युमिनियम पिघलते ही "
     "हवा से ऑक्सीजन खींच कर ऑक्साइड की परत बना लेता है; थोड़ी सी भी एक्टिव "
     "गैस हो तो वेल्ड में छेद (porosity) रह जाते हैं और जोड़ कमज़ोर हो जाता है।\n\n"
     "आम दिक्कतें: गैस सिलेंडर ख़ाली या फ़्लो बहुत कम (बीड काली और porous हो "
     "जाती है), पंखे या हवा के झोंके से गैस उड़ जाना, फ़ीड रोलर या लाइनर में "
     "तार का फिसलना, कॉन्टैक्ट टिप घिस कर बड़ी हो जाना जिससे आर्क इधर-उधर "
     "भागे, अर्थ क्लैंप ढीला या पेंट पर लगा होना।"),

    ("Welding", "MAG Welding (Metal Active Gas)",
     "MAG uses the SAME machine, the same wire feed and the same torch as MIG. "
     "Only the GAS is different - that is the whole difference between the two "
     "names.\n\n"
     "The A means ACTIVE. The gas is either pure CO2, or a mix of Argon with "
     "CO2 (usually 80% Argon + 20% CO2). An active gas DOES take part in the "
     "arc: CO2 breaks apart in the heat and releases oxygen.\n\n"
     "That sounds bad, but on mild steel it is useful. The arc runs hotter, "
     "penetration goes deeper, and the small amount of oxygen helps the molten "
     "pool wet and spread properly. This is why almost all mild-steel work - "
     "seat frames, brackets, rails, jigs, trolleys - is done with MAG.\n\n"
     "Pure CO2 is the cheapest and gives the deepest penetration, but the arc "
     "is rough and throws a lot of spatter. An Argon+CO2 mix costs more, but "
     "the arc is steady, the bead looks clean and there is far less spatter to "
     "chip off afterwards.\n\n"
     "NOTE: on the shop floor everyone calls both of them MIG. Strictly "
     "speaking, if the job is plain steel and the bottle has CO2 in it, that "
     "is MAG.\n\n"
     "COMMON FAULTS: heavy spatter from too much CO2 or wrong voltage / wire "
     "speed setting, gas flow set TOO HIGH (it becomes turbulent and actually "
     "drags air in - weld goes porous), oily or rusty job, nozzle choked with "
     "old spatter so the gas cannot spread.",
     "MAG में मशीन, वायर फ़ीड और टॉर्च — सब कुछ MIG जैसा ही होता है। सिर्फ़ "
     "गैस अलग होती है — दोनों नामों में बस इतना ही फ़र्क़ है।\n\n"
     "A मतलब ACTIVE (सक्रिय)। गैस या तो शुद्ध CO2 होती है, या Argon में CO2 "
     "मिला कर (आम तौर पर 80% Argon + 20% CO2)। एक्टिव गैस आर्क में हिस्सा "
     "लेती है — गर्मी में CO2 टूटता है और ऑक्सीजन छोड़ता है।\n\n"
     "सुनने में यह ख़राब लगता है, पर माइल्ड स्टील पर यही फ़ायदेमंद है। आर्क "
     "ज़्यादा गरम चलता है, पेनिट्रेशन गहरा जाता है, और थोड़ी सी ऑक्सीजन पिघले "
     "पूल को ठीक से फैलने में मदद करती है। इसीलिए माइल्ड स्टील का लगभग सारा "
     "काम — सीट फ़्रेम, ब्रैकेट, रेल, जिग, ट्रॉली — MAG से होता है।\n\n"
     "शुद्ध CO2 सबसे सस्ती है और पेनिट्रेशन सबसे गहरा देती है, पर आर्क खुरदरा "
     "रहता है और छींटे (spatter) बहुत उड़ते हैं। Argon+CO2 का मिक्स महँगा है, "
     "पर आर्क स्थिर रहता है, बीड साफ़ दिखती है और बाद में छीलने लायक़ spatter "
     "बहुत कम होता है।\n\n"
     "ध्यान दें: शॉप फ़्लोर पर दोनों को ही MIG कह देते हैं। सही मायने में, "
     "अगर जॉब सादा स्टील है और सिलेंडर में CO2 है — तो वह MAG है।\n\n"
     "आम दिक्कतें: ज़्यादा CO2 या ग़लत वोल्टेज / वायर स्पीड से बहुत spatter, "
     "गैस फ़्लो ज़रूरत से ज़्यादा (turbulent होकर उल्टा हवा खींच लेता है — "
     "वेल्ड porous), जॉब पर तेल या जंग, नोज़ल में पुराना spatter जमा होने से "
     "गैस का न फैल पाना।"),

    ("Welding", "Projection Welding",
     "Projection welding is a RESISTANCE welding process - the same family as "
     "spot welding. There is NO SHIELDING GAS AT ALL, and no filler wire.\n\n"
     "Small raised bumps called PROJECTIONS are pressed into one of the parts "
     "beforehand - or the part already carries them. A weld nut, for example, "
     "comes from the supplier with three or four projections on its face.\n\n"
     "The two parts are clamped between copper electrodes. Because only the "
     "projections are touching, ALL the current is forced through those few "
     "small points. They heat up instantly, melt, and collapse under the "
     "electrode force - and that collapse is the weld.\n\n"
     "Three things control the weld and nothing else: CURRENT, TIME and "
     "ELECTRODE FORCE. Change any one of the three and the weld changes.\n\n"
     "WHY NO GAS IS NEEDED: the molten metal never sees the air. It is trapped "
     "between the two sheets with the electrodes pressing down on top. Air "
     "cannot reach it, so there is nothing to shield it from.\n\n"
     "This is the process used to put weld nuts, studs and brackets onto sheet "
     "metal - which is why it is everywhere on seat-rail and bracket lines.\n\n"
     "COMMON FAULTS: electrode tips worn or mushroomed (current spreads out "
     "and the weld goes weak), projection height not uniform on the incoming "
     "part, oil / rust / paint on the mating surface, EXPULSION (metal "
     "splashing out) from too much current or too little force, blocked water "
     "cooling so the tips overheat, loose or worn electrode holder.",
     "प्रोजेक्शन वेल्डिंग एक RESISTANCE वेल्डिंग प्रोसेस है — स्पॉट वेल्डिंग "
     "वाले ही परिवार की। इसमें शील्डिंग गैस बिल्कुल नहीं लगती, और भरने वाला "
     "तार भी नहीं।\n\n"
     "एक पार्ट पर पहले से छोटे उभार बनाए जाते हैं जिन्हें PROJECTION कहते हैं "
     "— या पार्ट पर वे पहले से होते हैं। जैसे weld nut सप्लायर से ही अपने "
     "चेहरे पर तीन-चार प्रोजेक्शन लेकर आता है।\n\n"
     "दोनों पार्ट कॉपर इलेक्ट्रोड के बीच दबाए जाते हैं। छूते सिर्फ़ प्रोजेक्शन "
     "हैं, इसलिए पूरा करंट उन्हीं थोड़े से बिंदुओं से गुज़रने को मजबूर होता है। "
     "वे तुरंत गरम होते हैं, पिघलते हैं, और इलेक्ट्रोड के दबाव में बैठ जाते हैं "
     "— यही बैठना ही वेल्ड है।\n\n"
     "वेल्ड सिर्फ़ तीन चीज़ों से तय होता है, और किसी से नहीं: CURRENT, TIME "
     "और ELECTRODE FORCE। तीनों में से एक भी बदला तो वेल्ड बदल जाएगा।\n\n"
     "गैस की ज़रूरत क्यों नहीं: पिघली धातु हवा देखती ही नहीं। वह दोनों शीट के "
     "बीच बंद रहती है और ऊपर से इलेक्ट्रोड दबा रहे होते हैं। हवा वहाँ तक "
     "पहुँच ही नहीं सकती, तो बचाने की ज़रूरत ही नहीं पड़ती।\n\n"
     "शीट मेटल पर weld nut, stud और ब्रैकेट लगाने का यही तरीक़ा है — इसीलिए "
     "सीट-रेल और ब्रैकेट लाइनों पर यह हर जगह मिलता है।\n\n"
     "आम दिक्कतें: इलेक्ट्रोड टिप घिस कर फैल जाना (करंट फैल जाता है और वेल्ड "
     "कमज़ोर), आने वाले पार्ट पर प्रोजेक्शन की ऊँचाई एक जैसी न होना, जुड़ने "
     "वाली सतह पर तेल / जंग / पेंट, ज़्यादा करंट या कम फ़ोर्स से EXPULSION "
     "(धातु का छिटकना), पानी की कूलिंग बंद होने से टिप का ज़्यादा गरम होना, "
     "इलेक्ट्रोड होल्डर का ढीला या घिसा होना।"),

    ("Welding", "Shielding Gas - which one and why",
     "WHY ANY GAS AT ALL: the moment metal melts it starts pulling oxygen and "
     "nitrogen out of the air. That leaves gas bubbles (porosity) inside the "
     "bead and makes the joint brittle. The shielding gas simply pushes the "
     "air out of the way until the pool freezes. Nothing more.\n\n"
     "ARGON - inert. Used for MIG on aluminium, stainless steel and copper. It "
     "is a heavy gas, so it settles over the pool and covers it well, and the "
     "arc is very stable.\n\n"
     "HELIUM - inert. Mixed with Argon for thick aluminium. It carries more "
     "heat, so the weld runs hotter and penetration improves.\n\n"
     "CO2 - active. Used for MAG on mild steel. Cheapest of all, deepest "
     "penetration, but rough arc and heavy spatter.\n\n"
     "ARGON + CO2 (usually 80/20) - active. The normal factory choice for mild "
     "steel. Steady arc, clean bead, far less spatter - at a higher gas cost.\n\n"
     "NO GAS - projection and spot welding. The melt is sealed between the two "
     "parts, so air never reaches it and there is nothing to shield.\n\n"
     "EASY WAY TO REMEMBER: an INERT gas only covers, it does not join in - "
     "use it on metals that hate oxygen (aluminium, stainless). An ACTIVE gas "
     "joins in and adds heat - use it on plain steel where a hotter, deeper "
     "weld is wanted.\n\n"
     "FLOW RATE matters as much as the gas itself. Too little and air gets in. "
     "But too MUCH is also wrong - a high flow turns turbulent and actually "
     "drags air into the shield. Around 12-15 litres/min suits most MIG/MAG "
     "work; go higher only when there is a real draught.\n\n"
     "COMMON FAULTS: wrong gas fitted for the job (Argon on mild steel gives a "
     "narrow, poorly wetted bead; CO2 on aluminium ruins it), flow set by guess "
     "instead of by the flowmeter, leaking hose or loose fitting (bottle "
     "empties with nothing to show for it), reading bottle pressure on the "
     "regulator and mistaking it for flow.",
     "गैस की ज़रूरत ही क्यों: धातु पिघलते ही हवा से ऑक्सीजन और नाइट्रोजन "
     "खींचने लगती है। इससे बीड के अंदर गैस के बुलबुले (porosity) रह जाते हैं "
     "और जोड़ भुरभुरा हो जाता है। शील्डिंग गैस का काम बस इतना है कि पूल के "
     "जमने तक हवा को दूर रखे। इससे ज़्यादा कुछ नहीं।\n\n"
     "ARGON — निष्क्रिय। एल्युमिनियम, स्टेनलेस स्टील और कॉपर की MIG के लिए। "
     "भारी गैस है, इसलिए पूल के ऊपर बैठ कर उसे अच्छे से ढक लेती है, और आर्क "
     "बहुत स्थिर रहता है।\n\n"
     "HELIUM — निष्क्रिय। मोटे एल्युमिनियम के लिए Argon में मिलाई जाती है। "
     "ज़्यादा गर्मी ले जाती है, इसलिए वेल्ड गरम चलता है और पेनिट्रेशन बढ़ता "
     "है।\n\n"
     "CO2 — सक्रिय। माइल्ड स्टील की MAG के लिए। सबसे सस्ती, पेनिट्रेशन सबसे "
     "गहरा, पर आर्क खुरदरा और spatter बहुत।\n\n"
     "ARGON + CO2 (आम तौर पर 80/20) — सक्रिय। माइल्ड स्टील के लिए फ़ैक्टरी की "
     "आम पसंद। आर्क स्थिर, बीड साफ़, spatter बहुत कम — गैस का ख़र्च ज़्यादा।\n\n"
     "गैस नहीं — प्रोजेक्शन और स्पॉट वेल्डिंग। पिघली धातु दोनों पार्ट के बीच "
     "बंद रहती है, हवा पहुँचती ही नहीं, तो बचाने को कुछ है ही नहीं।\n\n"
     "याद रखने का आसान तरीक़ा: निष्क्रिय (inert) गैस सिर्फ़ ढकती है, हिस्सा "
     "नहीं लेती — उन धातुओं पर लगाइए जिन्हें ऑक्सीजन से चिढ़ है (एल्युमिनियम, "
     "स्टेनलेस)। सक्रिय (active) गैस हिस्सा भी लेती है और गर्मी भी देती है — "
     "सादे स्टील पर, जहाँ गरम और गहरा वेल्ड चाहिए।\n\n"
     "फ़्लो रेट गैस जितना ही ज़रूरी है। कम होगा तो हवा घुस जाएगी। पर ज़्यादा "
     "होना भी ग़लत है — तेज़ फ़्लो turbulent होकर उल्टा हवा खींच लेता है। "
     "ज़्यादातर MIG/MAG काम के लिए 12–15 लीटर/मिनट ठीक रहता है; इससे ऊपर तभी "
     "जब सच में हवा का झोंका आ रहा हो।\n\n"
     "आम दिक्कतें: जॉब के हिसाब से ग़लत गैस लगी होना (माइल्ड स्टील पर Argon "
     "से बीड पतली और ठीक से न फैलने वाली बनती है; एल्युमिनियम पर CO2 सब "
     "बिगाड़ देती है), फ़्लो अंदाज़े से सेट करना — फ़्लोमीटर से नहीं, पाइप "
     "में लीक या ढीली फ़िटिंग (सिलेंडर ख़ाली और काम कुछ नहीं), रेगुलेटर पर "
     "सिलेंडर का प्रेशर देख कर उसे फ़्लो समझ लेना।"),
]
